// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpbM8a2a7PN1AP2uEAAsDQKQ9bHqPX8lY',
    appId: '1:141677180259:web:f5814ce61f409c093a8f56',
    messagingSenderId: '141677180259',
    projectId: 'notesapp-a5d73',
    authDomain: 'notesapp-a5d73.firebaseapp.com',
    storageBucket: 'notesapp-a5d73.firebasestorage.app',
    measurementId: 'G-XE0ZQ71LSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo9IAeojbM-9tw-XU9QJsCzB-fFSZrECU',
    appId: '1:141677180259:android:46c79b00158354c23a8f56',
    messagingSenderId: '141677180259',
    projectId: 'notesapp-a5d73',
    storageBucket: 'notesapp-a5d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXsuKzIAwwC1BdW6HLg3DbBePtdImfK4',
    appId: '1:141677180259:ios:ba1806eab4fa6ff33a8f56',
    messagingSenderId: '141677180259',
    projectId: 'notesapp-a5d73',
    storageBucket: 'notesapp-a5d73.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrXsuKzIAwwC1BdW6HLg3DbBePtdImfK4',
    appId: '1:141677180259:ios:ba1806eab4fa6ff33a8f56',
    messagingSenderId: '141677180259',
    projectId: 'notesapp-a5d73',
    storageBucket: 'notesapp-a5d73.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpbM8a2a7PN1AP2uEAAsDQKQ9bHqPX8lY',
    appId: '1:141677180259:web:ea51691b40ad88443a8f56',
    messagingSenderId: '141677180259',
    projectId: 'notesapp-a5d73',
    authDomain: 'notesapp-a5d73.firebaseapp.com',
    storageBucket: 'notesapp-a5d73.firebasestorage.app',
    measurementId: 'G-EG2CR03VD5',
  );
}
